### ISSUE TITLE
Critical: Cannot log in anymore

### ISSUE THREAD

**Issue by sagidayan** [liranbg/JceManager#31]
The JCE blocked our methods to connect.

we have 2 choices:
- to find a patch to fix the block
- To create a new front end that will use the API that i Found (from mobile app).

@liranbg Let me know what you think.. the finals are coming fast and we need to kick some :zap: ass

**Comment by liranbg** [comment]
Fixed. :)

**Comment by sagidayan** [comment]
:fire: on You!

**Comment by sagidayan** [comment]
Still not working
